#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy Flask App to AWS ElasticBeanstalk
#env:
# Version      Date        Info
# 1.0        09-03-2020    Initial Version
#
# Made by Ruslan Riznyk Replica (c) 2020
#---------------------------------------------------------------------
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "rool-github-action-bucket"
  EB_APPLICATION_NAME      : "MyFlaskApp"
  EB_ENVIRONMENT_NAME      : "Myflaskapp-env" 
  DEPLOY_PACKAGE_NAME      : "flask-app-${{ github.sha }}.zip"
  AWS_REGION_NAME          : "eu-central-1"
  
on:
  push:
    branches: 
      - master

jobs:
  my_ci_pipeline:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
    
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}
             
      - name: Copy our Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
      - name: Print CI message 
        run : echo "CI Pipeline has finished successfully"
    
    
    
    
    
    
    
    
    
    
    
    
        
               
          
          
          
